[package]
name = "dice-rs"
version = "0.1.0"
authors = ["deppong <30512867+deppong@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.5.4"
rand = "0.7.3"
